apiVersion: v1
kind: Service
metadata:
  name: v-console-prod-service
  labels:
    app: v-console-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.105
  externalIPs:
  - 10.24.24.105
  ports:
  - name: http
    port: 80 #local out port
    protocol: TCP
    targetPort: 80 # container port
  selector:
    app: v-console-prod #find all pod with app name
  sessionAffinity: None
